### ISSUE TITLE
v0.99 io.airlift.configuration.testing.ConfigAssertions crash in Java 8 

### ISSUE THREAD

**Issue by shootingsyh** [airlift/airlift#265]
The exception is:
java.lang.IllegalArgumentException: null
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
	at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:285)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:679)
	at io.airlift.configuration.testing.ConfigAssertions.recordDefaults(ConfigAssertions.java:276)
	at com.facebook.di.smc.TestSmcUnionDataSourceConfig.testDefaults(TestSmcUnionDataSourceConfig.java:16)
which should related with an old version of cglib. However, cglib doesn't have an official version to support Java 8. 
Someone provided a mitigation: https://jira.codehaus.org/browse/EASYMOCK-140
but not work for airlift as if I exclude the current version of cglib, there will be runtime error:
java.lang.NoClassDefFoundError: net/sf/cglib/proxy/Callback
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at bla.testDefaults(TestBlaConfig.java:15)

**Comment by electrum** [comment]
Can you give us some sample code or add a unit test that reproduces the issue? We build, release and use Airlift on Java 8 with many config classes and have never seen this.=

**Comment by shootingsyh** [comment]
Here is an example:
public class S1{
    @Config("tier-name")
    public S1 setTierName(final String tierName)
    {
        return this;
    }
}
public class S2 extends S1 { 
    @Config("tier-name")
    @Override
    public S2 setTierName(final String tierName)
    {
        return this;
    }
}
ConfigAssertions.recordDefaults(S2.class);
The last line will cause the exception above. The problem happens when an inherited class override  parent's function for same config...

**Comment by electrum** [comment]
Sorry for the delay. We might need to wait for cglib/cglib#20, though we're using a very old version of cglib that still depends on ASM 3. Upgrading to cglib 3.1 which uses ASM 4 might fix this.
