### ISSUE TITLE
TestAnnouncer::addAnnouncementAfterStart is flaky

### ISSUE THREAD

**Issue by flakycov** [airlift/airlift#546]
Title: TestAnnouncer::addAnnouncementAfterStart is flaky

`TestAnnouncer::addAnnouncementAfterStart` failed for us on commit 835baac but did not fail [on the corresponding run on Travis](https://travis-ci.org/airlift/airlift/builds/259538445):

```
Tests run: 60, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.268 sec <<< FAILURE! - in TestSuite
addAnnouncementAfterStart(io.airlift.discovery.client.TestAnnouncer)  Time elapsed: 3.852 sec  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [1]
	at io.airlift.discovery.client.TestAnnouncer.assertAnnounced(TestAnnouncer.java:158)
	at io.airlift.discovery.client.TestAnnouncer.addAnnouncementAfterStart(TestAnnouncer.java:131)
```
Our investigation shows that this test is likely flaky. We set up our build environment to be as close to your Travis environment as possible, using Ubuntu 14.04.5 LTS, Java HotSpot 1.8.0_31-b13 and Maven 3.3.9.

**Comment by flakycov** [comment]
We noticed that if this test is made to sleep for less time, e.g., change `Thread.sleep(100);` to `Thread.sleep(5)`, then it flakes more often.
