### ISSUE TITLE
Add support for validation Optionals in configuration

### ISSUE THREAD

**Issue by kokosing** [airlift/airlift#682]
The idea is to run validation for enclosed type within a Optional if the value is present.

Having support for optionals could make `@NotNull` annotation to become obsolete, because validation could always assume that returned value should be not null. Optionals are also much better to handle absent values, than nullable return value.

```
class SomeConfig {
    Duration duration;

    @MinDuration("1ms")
    public Optional<Duration> getDuration()
    {
        return Optional.ofNullable(duration);
    }

    @Config("duration")
    public SomeConfig setDuration(Duration duration)
    {
        this.duration = duration;
        return this;
    }
}
```

Currently it throws:
```
javax.validation.UnexpectedTypeException: No validator could be found for type java.util.Optional<io.airlift.units.Duration>. See: @MinDuration at public java.util.Optional com.facebook.presto.plugin.base.security.FileBasedAccessControlConfig.getRefreshPeriod()
	at org.apache.bval.jsr.ConstraintValidation.checkOneType(ConstraintValidation.java:320)
	at org.apache.bval.jsr.ConstraintValidation.getConstraintValidator(ConstraintValidation.java:255)
	at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:157)
	at org.apache.bval.jsr.ConstraintValidation.validate(ConstraintValidation.java:144)
	at org.apache.bval.util.ValidationHelper.validateProperty(ValidationHelper.java:234)
	at org.apache.bval.jsr.ClassValidator.validateBean(ClassValidator.java:462)
	at org.apache.bval.jsr.ClassValidator.validateBeanNet(ClassValidator.java:409)
	at org.apache.bval.jsr.ClassValidator.validateBeanWithGroups(ClassValidator.java:154)
	at org.apache.bval.jsr.ClassValidator.validate(ClassValidator.java:142)
	at io.airlift.configuration.ConfigurationFactory.validate(ConfigurationFactory.java:414)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:387)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:299)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:294)
	at com.facebook.presto.plugin.base.security.TestFileBasedAccessControlConfig.newInstance(TestFileBasedAccessControlConfig.java:73)
	at com.facebook.presto.plugin.base.security.TestFileBasedAccessControlConfig.lambda$testValidation$0(TestFileBasedAccessControlConfig.java:58)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:60)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:713)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1135)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1061)
	at com.facebook.presto.plugin.base.security.TestFileBasedAccessControlConfig.testValidation(TestFileBasedAccessControlConfig.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by electrum** [comment]
We’ll need to switch to Hibernate Validator which implements JSR-380, the 2.0 version of the spec supporting Optional. Looks like Apache hasn’t updated for that.

**Comment by dain** [comment]
BVAL that supports the new spec was released last week. http://bval.apache.org/downloads.html

-dain

**Comment by dain** [comment]
@electrum you must have an old cache of that page, it says "Apache BVal 2.0.0 - Java 8 - Bean Validation v2.0 - Released Oct 28 2018"

**Comment by electrum** [comment]
@dain Thanks, I refreshed and it shows up now. For some reason mobile Safari kept showing the old one.

**Comment by findepi** [comment]
@kokosing the proper syntax would be

```
public Optional<@MinDuration("1ms") Duration> getDuration()
```

This should work now, since https://github.com/airlift/airbase/pull/167

**Comment by kokosing** [comment]
Thanks!
