### ISSUE TITLE
Exception while getting 75th Percentile with 2 values

### ISSUE THREAD

**Issue by prakashgayasen** [airlift/airlift#862]
While getting 75th percentile in a distribution with non-zero alpha and exactly 2 values. The code throws exception
```
    @Test
    public void testTwoValues() {
        Distribution d = new Distribution(ExponentialDecay.oneMinute());
        d.add(10);
        d.add(10);
        d.getP75();
    }
```
Stack trace is
```
java.lang.AssertionError
	at io.airlift.stats.TDigest.valueAt(TDigest.java:308)
	at io.airlift.stats.DecayTDigest.valueAt(DecayTDigest.java:127)
	at io.airlift.stats.Distribution.getP75(Distribution.java:105)
	at io.airlift.stats.TestDistribution.testTwoValues(TestDistribution.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```
I believe the issue is with [TDigest:279](https://github.com/airlift/airlift/blob/d2267de28b26bd41aa5ce0b6e0c5c5a68e109ba7/stats/src/main/java/io/airlift/stats/TDigest.java#L279)
The comparator should be >=
```
weightSoFar + delta >= offset
```
I can create a pull request with suggested fix. Please check if the logic is fine or am I missing any flow.

**Comment by martint** [comment]
Yes, that fix is correct. Thanks for finding and reporting the issue!

Also, here's a reproduction of the problem directly with TDigest. Please include it as test with the fix:

```java
TDigest digest = new TDigest();
digest.add(10, 99999.999999999);
digest.add(10, 99999.999999999);
digest.valueAt(0.75);
```

**Comment by prakashgayasen** [comment]
Closing since PR is merged
